In [104]:
# Задание 1 Создать кортеж с числами от 5 до 9, затем создать словарь,
# где ключами будут элементы этого кортежа, а значениями - списки, 
# содержащие числа от 0 до значения текущего ключа.
# Напечатать пары ключ-значение данного словаря, пронумеровав их

myTup = tuple(range(5, 10))
myDict = {}

#Инициализируем словарь
for tupItem in myTup:
    myDict[tupItem] = list(range(0, tupItem + 1))

#Выводим содержимое словаря
n = 1
for key, value in myDict.items():
    print("Пара ключ-значение номер {0}. Ключ: {1}, значение: {2}. \n".format(n, key, value))
    n += 1

Пара ключ-значение номер 1. Ключ: 5, значение: [0, 1, 2, 3, 4, 5]. 

Пара ключ-значение номер 2. Ключ: 6, значение: [0, 1, 2, 3, 4, 5, 6]. 

Пара ключ-значение номер 3. Ключ: 7, значение: [0, 1, 2, 3, 4, 5, 6, 7]. 

Пара ключ-значение номер 4. Ключ: 8, значение: [0, 1, 2, 3, 4, 5, 6, 7, 8]. 

Пара ключ-значение номер 5. Ключ: 9, значение: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. 



In [102]:
# Задание 2. Создать переменную строкового типа с вашими ФИО. 
# Посчитать количество вхождений в эту строку буквы "а",
# заменить каждое вхождение на символ "@".
# Разбить исходную строку по пробелам в список.
# С помощью функции строк format() напечатать "Меня зовут ~имя", 
# используя обращение к списку из прошлого предложения.

fullName = "Власенко Дмитрий Андреевич"
print("Количество вхождений буквы \"а\" в мое ФИО: {}\n".format(fullName.count("а")))

changedName = fullName.replace("а", "@")
print("Имя после замены символов: {}\n".format(changedName))

nameList = fullName.split(" ")
print("Меня зовут {}".format(nameList[1]))

Количество вхождений буквы "а" в мое ФИО: 1

Имя после замены символов: Вл@сенко Дмитрий Андреевич

Меня зовут Дмитрий


In [103]:
# Задание 3. Установить модуль itertools. Если будет ошибка,
# что такого нет, то попробуйте more-itertools.
# Найти перестановки из списка с ФИО Задания 2.

import itertools as it

permutationList = list(it.permutations(nameList))
print("Все перестановки из списка с ФИО:\n\n {}".format(permutationList))

Все перестановки из списка с ФИО:

 [('Власенко', 'Дмитрий', 'Андреевич'), ('Власенко', 'Андреевич', 'Дмитрий'), ('Дмитрий', 'Власенко', 'Андреевич'), ('Дмитрий', 'Андреевич', 'Власенко'), ('Андреевич', 'Власенко', 'Дмитрий'), ('Андреевич', 'Дмитрий', 'Власенко')]


In [105]:
#Задание 4. Вычислить e^(sin(4^2 - ln(85)))

import math

result = math.exp(math.sin(4**2 - math.log(85)))
print("Полученный результат: {}".format(result))

Полученный результат: 0.4289944869247778


In [106]:
# Задание 5. Создать 2 двумерных массива (матрицы) произвольного размера 
# (главное, чтобы было одинаковое количество строк),
# в одном из которых все значения - единицы, а в другом - единицы
# на главной диагонали, а остальные значения нулевые.
# Соедините эти матрицы в одну так, чтобы число строк
# осталось исходным, а число столбцов стало суммарным.

import numpy as np

rowCount = 5
firstMatrix = np.ones((rowCount, 9)) # матрица из единиц
print("Матрица 1: \n\n{}\n".format(firstMatrix))

secondMatrix = np.eye(rowCount, rowCount) # матрица с единицами по главной диагонали
print("Матрица 2: \n\n{}\n".format(secondMatrix))

result = np.concatenate((firstMatrix, secondMatrix), axis = 1)
print("Итоговая матрица: \n\n{}".format(result))

Матрица 1: 

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Матрица 2: 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Итоговая матрица: 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1.]]
